<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>First exercice</title>
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs5/jqc-1.12.4/dt-1.12.1/datatables.min.css" />
  <link rel="stylesheet" href=".\libs\bootstrap\css\bootstrap.css" />

  <link rel="stylesheet" type="text/css" href="./style.css">

</head>


<body class="container" id="cont">
  <main>
    <table id="table" class="table">
      <thead>
        <th>ID</th>
        <th>Nom</th>
        <th>Image</th>
        <th>Description</th>
      </thead>
    </table>
  </main>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/v/bs5/jqc-1.12.4/dt-1.12.1/datatables.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>


  <script type="text/javascript" src="app.js"></script>

</body>

</html>